# Generated by Django 4.0.2 on 2022-02-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(default=None, help_text='Эта иконка будет отображаться на сайте. Нажав на эту иконку, пользователь будет отправлен по ссылке.', upload_to='icons/%Y%m%d/', verbose_name='Иконка соц. сети'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(help_text="Вставьте полную ссылку. Например 'https://www.instagram.com/instagram/'", max_length=50, verbose_name='Ссылка'),
        ),
    ]
