# Generated by Django 4.0.2 on 2022-02-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_socialmedia_icon_alter_socialmedia_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='address_en',
            field=models.CharField(default=None, max_length=50, verbose_name='Адрес (АНГ)'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_ru',
            field=models.CharField(default=None, max_length=50, verbose_name='Адрес (РУС)'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_uz',
            field=models.CharField(default=None, max_length=50, verbose_name='Адрес (УЗБ)'),
        ),
    ]
