# Generated by Django 4.0.2 on 2022-02-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPage',
            new_name='MetaTag',
        ),
        migrations.AlterModelOptions(
            name='metatag',
            options={'verbose_name': 'Мета-теги', 'verbose_name_plural': 'Мета-теги'},
        ),
    ]
