# Generated by Django 4.0.2 on 2022-02-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='', verbose_name='Иконка сайта')),
            ],
            options={
                'verbose_name': 'Иконка сайта',
            },
        ),
        migrations.CreateModel(
            name='TagForHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=25, verbose_name='Для чего нужен этот тег?')),
                ('code', models.TextField(verbose_name='HTML-Код, для <head> элемента:')),
            ],
            options={
                'verbose_name': 'Тэг для <head>',
            },
        ),
    ]
