# Generated by Django 4.0.2 on 2022-02-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favicon',
            options={'verbose_name': 'Favicon', 'verbose_name_plural': 'Favicon'},
        ),
        migrations.AlterModelOptions(
            name='tagforhead',
            options={'verbose_name': 'Тэги для <head>', 'verbose_name_plural': 'Тэги для <head>'},
        ),
    ]
