# Generated by Django 4.0.2 on 2022-02-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0002_alter_favicon_options_alter_tagforhead_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='favicon',
            field=models.ImageField(upload_to='img/%Y%m%d/', verbose_name='Иконка сайта'),
        ),
    ]
