# Generated by Django 3.2 on 2022-02-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0003_alter_favicon_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_ru', models.CharField(max_length=120, verbose_name='Заголовок (РУС)')),
                ('text_ru', models.TextField(verbose_name='Текст заголовка (РУС)')),
                ('header_uz', models.CharField(max_length=120, verbose_name='Заголовок (УЗБ)')),
                ('text_uz', models.TextField(verbose_name='Текст заголовка (УЗБ)')),
                ('header_en', models.CharField(max_length=120, verbose_name='Заголовок (АНГ)')),
                ('text_en', models.TextField(verbose_name='Текст заголовка (АНГ)')),
                ('image', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
            ],
            options={
                'verbose_name': 'Первый блок',
                'verbose_name_plural': 'Первый блок',
            },
        ),
        migrations.CreateModel(
            name='SecondBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_ru', models.CharField(max_length=120, verbose_name='Заголовок (РУС)')),
                ('eader_uz', models.CharField(max_length=120, verbose_name='Заголовок (УЗБ)')),
                ('eader_en', models.CharField(max_length=120, verbose_name='Заголовок (АНГ)')),
                ('image1', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('text1_ru', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (РУС)')),
                ('text1_uz', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (УЗБ)')),
                ('text1_en', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (АНГ)')),
                ('image2', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('text2_ru', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (РУС)')),
                ('text2_uz', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (УЗБ)')),
                ('text2_en', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (АНГ)')),
                ('image3', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('text3_ru', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (РУС)')),
                ('text3_uz', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (УЗБ)')),
                ('text3_en', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (АНГ)')),
                ('image4', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('text4_ru', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (РУС)')),
                ('text4_uz', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (УЗБ)')),
                ('text4_en', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (АНГ)')),
                ('image5', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('text5_ru', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (РУС)')),
                ('text5_uz', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (УЗБ)')),
                ('text5_en', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (АНГ)')),
                ('image6', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('text6_ru', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (РУС)')),
                ('text6_uz', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (УЗБ)')),
                ('text6_en', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (АНГ)')),
                ('image7', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('text7_ru', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (РУС)')),
                ('text7_uz', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (УЗБ)')),
                ('text7_en', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (АНГ)')),
                ('image8', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('text8_ru', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (РУС)')),
                ('text8_uz', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (УЗБ)')),
                ('text8_en', models.CharField(help_text='Текст будет появляться при навдении на картинку', max_length=30, verbose_name='Текст (АНГ)')),
            ],
            options={
                'verbose_name': 'Второй блок',
                'verbose_name_plural': 'Второй блок',
            },
        ),
        migrations.CreateModel(
            name='ThirdBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_ru', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('eader_uz', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('eader_en', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('image1', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('image2', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('image3', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('image4', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('image5', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('image6', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('image7', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
                ('image8', models.ImageField(upload_to='img/mainpage/%Y%m%d/')),
            ],
            options={
                'verbose_name': 'Третий блок',
                'verbose_name_plural': 'Третий блок',
            },
        ),
    ]
