# Generated by Django 3.2 on 2022-02-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSettings', '0004_firstblock_secondblock_thirdblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondblock',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='secondblock',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='secondblock',
            name='text7_en',
        ),
        migrations.RemoveField(
            model_name='secondblock',
            name='text7_ru',
        ),
        migrations.RemoveField(
            model_name='secondblock',
            name='text7_uz',
        ),
        migrations.RemoveField(
            model_name='secondblock',
            name='text8_en',
        ),
        migrations.RemoveField(
            model_name='secondblock',
            name='text8_ru',
        ),
        migrations.RemoveField(
            model_name='secondblock',
            name='text8_uz',
        ),
        migrations.AlterField(
            model_name='firstblock',
            name='image',
            field=models.ImageField(upload_to='img/mainpage/%Y%m%d/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='eader_en',
            field=models.CharField(max_length=120, verbose_name='Заголовок (АНГ)'),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='eader_uz',
            field=models.CharField(max_length=120, verbose_name='Заголовок (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='thirdblock',
            name='header_ru',
            field=models.CharField(max_length=120, verbose_name='Заголовок (РУС)'),
        ),
    ]
