# Generated by Django 4.0.2 on 2022-02-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_metatags_remove_service_meta_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='MetaTags',
        ),
    ]
