# Generated by Django 4.0.2 on 2022-02-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_metatag_delete_metatags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metatag',
            options={'verbose_name': 'Мета-теги', 'verbose_name_plural': 'Мета-теги'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
    ]
