# Generated by Django 4.0.2 on 2022-02-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_metatag_options_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='desciption',
            field=models.TextField(default=None, verbose_name='Описание услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=None, upload_to='img/services/%Y%m%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.CharField(max_length=50, verbose_name='Название услуги'),
        ),
    ]
