# Generated by Django 4.0.2 on 2022-02-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_desciption_service_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='desciption',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='desciption_en',
            field=models.TextField(default=None, verbose_name='Краткое описание услуги (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='desciption_ru',
            field=models.TextField(default=None, verbose_name='Краткое описание услуги (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='desciption_uz',
            field=models.TextField(default=None, verbose_name='Краткое описание услуги (UZ)'),
        ),
        migrations.AddField(
            model_name='service',
            name='image1',
            field=models.ImageField(default=None, upload_to='img/services/%Y%m%d/', verbose_name='Фото1'),
        ),
        migrations.AddField(
            model_name='service',
            name='image2',
            field=models.ImageField(default=None, upload_to='img/services/%Y%m%d/', verbose_name='Фото2'),
        ),
        migrations.AddField(
            model_name='service',
            name='long_desciption_en',
            field=models.TextField(default=None, verbose_name='Полное описание услуги (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='long_desciption_ru',
            field=models.TextField(default=None, verbose_name='Полное описание услуги (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='long_desciption_uz',
            field=models.TextField(default=None, verbose_name='Полное описание услуги (UZ)'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_en',
            field=models.CharField(default=None, max_length=50, verbose_name='Название услуги (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_ru',
            field=models.CharField(default=None, max_length=50, verbose_name='Название услуги (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_uz',
            field=models.CharField(default=None, max_length=50, verbose_name='Название услуги (UZ)'),
        ),
    ]
