# Generated by Django 4.0.2 on 2022-02-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_desciption_remove_service_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='desciption_en',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='desciption_ru',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='desciption_uz',
            new_name='description_uz',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='long_desciption_en',
            new_name='long_description_en',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='long_desciption_ru',
            new_name='long_description_ru',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='long_desciption_uz',
            new_name='long_description_uz',
        ),
    ]
