# Generated by Django 4.0.2 on 2022-02-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_service_en_alter_service_service_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(default=None, verbose_name='Краткое описание услуги (АНГ)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=models.TextField(default=None, verbose_name='Краткое описание услуги (РУС)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_uz',
            field=models.TextField(default=None, verbose_name='Краткое описание услуги (УЗ)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='long_description_en',
            field=models.TextField(default=None, verbose_name='Полное описание услуги (АНГ)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='long_description_ru',
            field=models.TextField(default=None, verbose_name='Полное описание услуги (РУС)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='long_description_uz',
            field=models.TextField(default=None, verbose_name='Полное описание услуги (УЗ)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_en',
            field=models.CharField(default=None, max_length=120, verbose_name='Название услуги (АНГ)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_ru',
            field=models.CharField(default=None, max_length=120, verbose_name='Название услуги (РУС)'),
        ),
    ]
