# Generated by Django 3.2 on 2022-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_service_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatag',
            name='name',
        ),
        migrations.AddField(
            model_name='metatag',
            name='metatag',
            field=models.TextField(default=None, help_text='Введите ключевые слова через запятую / Предложением', verbose_name='Keywords (Через запятую / предложением'),
        ),
    ]
