# Generated by Django 4.0.2 on 2022-02-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_ru', models.CharField(default=None, max_length=50, verbose_name='Заголовок')),
                ('text_ru', models.TextField(default=None, verbose_name='Текст')),
                ('image_ru', models.ImageField(default=None, upload_to='img/about/%Y%m%d/', verbose_name='Картинка')),
                ('header_uz', models.CharField(default=None, max_length=50, verbose_name='Заголовок')),
                ('text_uz', models.TextField(default=None, verbose_name='Текст')),
                ('image_uz', models.ImageField(default=None, upload_to='img/about/%Y%m%d/', verbose_name='Картинка')),
                ('header_en', models.CharField(default=None, max_length=50, verbose_name='Заголовок')),
                ('text_en', models.TextField(default=None, verbose_name='Текст')),
                ('image_en', models.ImageField(default=None, upload_to='img/about/%Y%m%d/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описание',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Имя и фамилия')),
                ('position', models.CharField(default=None, max_length=30, verbose_name='Должность')),
                ('image', models.ImageField(default=None, upload_to='img/about/team/%Y%m%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
