# Generated by Django 4.0.2 on 2022-02-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='image_en',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image_ru',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image_uz',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='header_en',
            field=models.CharField(default=None, max_length=50, verbose_name='Заголовок (АНГ)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='header_ru',
            field=models.CharField(default=None, max_length=50, verbose_name='Заголовок (РУС)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='header_uz',
            field=models.CharField(default=None, max_length=50, verbose_name='Заголовок (УЗБ)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text_en',
            field=models.TextField(default=None, verbose_name='Текст (АНГ)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text_ru',
            field=models.TextField(default=None, verbose_name='Текст (РУС)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text_uz',
            field=models.TextField(default=None, verbose_name='Текст (УЗБ)'),
        ),
    ]
