# Generated by Django 4.0.2 on 2022-02-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_rename_image_en_aboutus_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image_webp',
            field=models.ImageField(default=None, help_text='Загрузите картинку в формате .webp', upload_to='img/about/%Y%m%d/', verbose_name='Картинка'),
        ),
    ]
