# Generated by Django 4.0.2 on 2022-02-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0004_alter_aboutus_image_webp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(default=None, max_length=50, verbose_name='Имя и фамилия (АНГ)'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(default=None, max_length=50, verbose_name='Имя и фамилия (РУС)'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_uz',
            field=models.CharField(default=None, max_length=50, verbose_name='Имя и фамилия (УЗБ)'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_en',
            field=models.CharField(default=None, max_length=30, verbose_name='Должность (АНГ)'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_ru',
            field=models.CharField(default=None, max_length=30, verbose_name='Должность (РУС)'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_uz',
            field=models.CharField(default=None, max_length=30, verbose_name='Должность (УЗБ)'),
        ),
    ]
