# Generated by Django 3.2 on 2022-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0005_remove_team_name_remove_team_position_team_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metatag', models.TextField(default=None, help_text='Введите ключевые слова через запятую / Предложением', verbose_name='Keywords (Через запятую / предложением')),
            ],
            options={
                'verbose_name': 'Мета-теги',
                'verbose_name_plural': 'Мета-теги',
            },
        ),
    ]
