# Generated by Django 4.0.2 on 2022-02-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_ru', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('header_uz', models.CharField(max_length=50, verbose_name='Заголовок (УЗБ)')),
                ('header_en', models.CharField(max_length=50, verbose_name='Заголовок (АНГ)')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
