# Generated by Django 4.0.2 on 2022-02-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_metatag_alter_portfolio_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(default=None, upload_to='img/portfolio/%Y%m%d/', verbose_name='Фото1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(default=None, upload_to='img/portfolio/%Y%m%d/', verbose_name='Фото2'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(default=None, upload_to='img/portfolio/%Y%m%d/', verbose_name='Фото3'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image4',
            field=models.ImageField(default=None, upload_to='img/portfolio/%Y%m%d/', verbose_name='Фото4'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image5',
            field=models.ImageField(default=None, upload_to='img/portfolio/%Y%m%d/', verbose_name='Фото5'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='header_en',
            field=models.CharField(max_length=120, verbose_name='Заголовок (АНГ)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='header_ru',
            field=models.CharField(max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='header_uz',
            field=models.CharField(max_length=120, verbose_name='Заголовок (УЗБ)'),
        ),
    ]
